### ISSUE TITLE
Issues with case sensitivity in the answer

### ISSUE THREAD

**Issue by jdillard** [Fusselwurm/nodebb-plugin-anti-spam-question#2]
First off, thanks for the plugin!

I just wanted to note that we were having issues with people registering, and it appears to be a case sensitivity issue. I was wondering if there could be a case sensitivity option, use `toLowerCase()` when comparing, and/or give the option of entering multiple acceptable answers for the question. If I had to share an opinion, I think the 2nd and 3rd options might be best.

Thanks again!

**Comment by Fusselwurm** [comment]
Personally, I've ditched usage of this plugin in favor of recaptcha. 
So uh I won't be adding any more features. 
If you oranyone want to take over as maintainer, I'd be happy to give you the necessary permissions.
